version: '3.4'

networks:
  dev_net:
    name: my-next14-demo-network
    driver: bridge

volumes:
  hot_reload_next:
    external: true
  hot_reload_node_modules:
    external: true
  postgres_16:
    external: true
  
services:
  postgres_db:
    container_name: my-next14-demo-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=Password12345!
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - dev_net
    ports:
      - 5432:5432
    volumes:
      - postgres_16:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3

  next_app:
    container_name: my-next14-demo-app
    image: mynext14demoapp
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:Password12345!@postgres_db:5432/mynext14demo?schema=public
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    networks:
      - dev_net
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - hot_reload_node_modules:/usr/src/app/node_modules
      - hot_reload_next:/usr/src/app/.next
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: true
